name: README Info Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-18.04
    steps:
      - uses: supernova-Z313/supernova-Z313@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Asia/Kolkata"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAILY_COMMIT: "True"
          SHOW_WEEKLY_COMMIT: "True"
          SHOW_LANGUAGE: "False"
          SHOW_TOTAL_CONTRIBUTIONS: "False"
